# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7QH0ZSQAnuSalDhbRdgAOQvvGN-dpY1
"""

import streamlit as st
import pandas as pd

from charts import *
from filters import apply_filters

# --------------------------------
# PAGE TITLE
# --------------------------------

st.set_page_config(
    page_title="Airline Safety Dashboard",
    layout="wide"
)

st.title("✈ Airline Safety Analysis Dashboard")
st.write(
    "Analysis of airline incidents, accidents and fatalities."
)

# --------------------------------
# LOAD DATA
# --------------------------------

df = pd.read_csv("airline_safety.csv")

# --------------------------------
# FEATURE ENGINEERING
# --------------------------------

df["total_incidents"] = (
    df["incidents_85_99"] +
    df["incidents_00_14"]
)

df["total_fatalities"] = (
    df["fatalities_85_99"] +
    df["fatalities_00_14"]
)

df["total_fatal_accidents"] = (
    df["fatal_accidents_85_99"] +
    df["fatal_accidents_00_14"]
)

# --------------------------------
# SIDEBAR FILTERS
# --------------------------------

st.sidebar.header("Filters")

selected_airlines = st.sidebar.multiselect(
    "Select Airline",
    options=df["airline"].unique()
)

fatality_range = st.sidebar.slider(
    "Fatality Range",
    int(df["total_fatalities"].min()),
    int(df["total_fatalities"].max()),
    (
        int(df["total_fatalities"].min()),
        int(df["total_fatalities"].max())
    )
)

filtered_df = apply_filters(
    df,
    selected_airlines,
    fatality_range
)

# --------------------------------
# KPI CARDS
# --------------------------------

c1, c2, c3, c4 = st.columns(4)

c1.metric(
    "Total Airlines",
    len(filtered_df)
)

c2.metric(
    "Total Incidents",
    int(filtered_df["total_incidents"].sum())
)

c3.metric(
    "Total Fatalities",
    int(filtered_df["total_fatalities"].sum())
)

c4.metric(
    "Average Fatalities",
    round(filtered_df["total_fatalities"].mean(),2)
)

st.divider()

# --------------------------------
# CHARTS
# --------------------------------

col1, col2 = st.columns(2)

with col1:
    st.pyplot(bar_chart(filtered_df))

with col2:
    st.pyplot(histogram(filtered_df))

col3, col4 = st.columns(2)

with col3:
    st.pyplot(scatter_plot(filtered_df))

with col4:
    st.pyplot(box_plot(filtered_df))

col5, col6 = st.columns(2)

with col5:
    st.pyplot(violin_plot(filtered_df))

with col6:
    st.pyplot(heatmap(filtered_df))

# --------------------------------
# DATA TABLE
# --------------------------------

st.subheader("Dataset Preview")

st.dataframe(filtered_df)

# --------------------------------
# INSIGHTS
# --------------------------------

st.subheader("Key Insights")

st.markdown("""
- Airlines with more incidents generally have higher fatalities.
- Several airlines reported zero fatalities.
- Fatality counts vary significantly across airlines.
- A small number of airlines account for most fatalities.
- Heatmap helps identify strong relationships among variables.
""")
