# -*- coding: utf-8 -*-
"""charts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUB-TLsIS3o9OlN3jOds3ibQ4-M-F7j7
"""

import matplotlib.pyplot as plt
import seaborn as sns

# BAR CHART
def bar_chart(df):

    fig, ax = plt.subplots(figsize=(10,5))

    top10 = df.sort_values(
        "total_fatalities",
        ascending=False
    ).head(10)

    sns.barplot(
        data=top10,
        x="total_fatalities",
        y="airline",
        ax=ax
    )

    ax.set_title("Top 10 Airlines by Fatalities")

    return fig


# HISTOGRAM
def histogram(df):

    fig, ax = plt.subplots()

    sns.histplot(
        df["total_fatalities"],
        bins=10,
        ax=ax
    )

    ax.set_title("Fatalities Distribution")

    return fig


# SCATTER
def scatter_plot(df):

    fig, ax = plt.subplots()

    sns.scatterplot(
        data=df,
        x="total_incidents",
        y="total_fatalities",
        ax=ax
    )

    ax.set_title("Incidents vs Fatalities")

    return fig


# BOX PLOT
def box_plot(df):

    fig, ax = plt.subplots()

    sns.boxplot(
        y=df["total_fatalities"],
        ax=ax
    )

    ax.set_title("Fatalities Box Plot")

    return fig


# VIOLIN PLOT
def violin_plot(df):

    fig, ax = plt.subplots()

    sns.violinplot(
        y=df["total_fatalities"],
        ax=ax
    )

    ax.set_title("Fatalities Violin Plot")

    return fig


# HEATMAP
def heatmap(df):

    fig, ax = plt.subplots(figsize=(10,6))

    corr = df.select_dtypes(include="number").corr()

    sns.heatmap(
        corr,
        annot=True,
        cmap="Blues",
        ax=ax
    )

    ax.set_title("Correlation Heatmap")

    return fig