# -*- coding: utf-8 -*-
"""filter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iiqNWK4VPexaYRMsDmf3sWs1M-uUqnvA
"""

import pandas as pd

def apply_filters(df, airlines, fatality_range):

    filtered_df = df.copy()

    if airlines:
        filtered_df = filtered_df[
            filtered_df["airline"].isin(airlines)
        ]

    filtered_df = filtered_df[
        (filtered_df["total_fatalities"] >= fatality_range[0]) &
        (filtered_df["total_fatalities"] <= fatality_range[1])
    ]

    return filtered_df